# Generated by Django 5.2.13 on 2026-05-16 09:26

import django.db.models.deletion
import pairing.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=pairing.models._generate_code, max_length=16, unique=True)),
                ('channel', models.CharField(db_index=True, max_length=32)),
                ('sender_id', models.CharField(db_index=True, max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField(default=pairing.models._default_expires_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'pairing_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'sender_id', 'status'], name='pairing_cod_channel_b305fd_idx'), models.Index(fields=['status', 'expires_at'], name='pairing_cod_status_b5b101_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovedSender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=32)),
                ('sender_id', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, help_text='Human-readable nickname for the device or person.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=256)),
                ('approved_via_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_senders', to='pairing.pairingcode')),
            ],
            options={
                'db_table': 'pairing_approved_sender',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'sender_id'], name='pairing_app_channel_3fe359_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('channel', 'sender_id'), name='uniq_active_sender_per_channel')],
            },
        ),
    ]
