# Generated by Django 5.2.13 on 2026-05-16 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('agent_id', models.CharField(blank=True, max_length=64)),
                ('model_provider', models.CharField(blank=True, max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0, help_text='Higher first. Dispatcher orders by (-priority, created_at).')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('claim_id', models.CharField(blank=True, help_text='Worker-supplied token identifying who owns the current claim.', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('stale_after_seconds', models.PositiveIntegerField(default=600, help_text='A claim with heartbeat older than this is reset to QUEUED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'kanban_task',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='kanban_task_status_8b7496_idx'), models.Index(fields=['status', 'heartbeat_at'], name='kanban_task_status_dab70f_idx')],
            },
        ),
    ]
