# Generated by Django 6.0.4 on 2026-04-17 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_future_queue_and_dream"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField()),
                ("source_code", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_tools",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "custom_tools_tool",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_validated"],
                        name="custom_tool_is_acti_0d7819_idx",
                    )
                ],
            },
        ),
    ]
