# Generated by Django 6.0.4 on 2026-04-17 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tool_id", models.CharField(max_length=128)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "output_summary",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("was_gated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool_id"], name="core_audit__tool_id_c703b3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_audit__created_ab8951_idx"
                    ),
                    models.Index(
                        fields=["session"], name="core_audit__session_b4ea50_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("web", "Web Chat"),
                            ("cron", "Cron"),
                            ("trigger", "Trigger"),
                        ],
                        max_length=16,
                    ),
                ),
                ("request", models.TextField()),
                ("result", models.TextField(blank=True, null=True)),
                ("tools_used", models.JSONField(blank=True, default=list)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "core_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="core_task_status_e18e62_idx"),
                    models.Index(
                        fields=["created_at"], name="core_task_created_9e4493_idx"
                    ),
                    models.Index(fields=["source"], name="core_task_source_d512ca_idx"),
                ],
            },
        ),
    ]
