# Generated by Django 6.0.4 on 2026-04-17 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tasks_and_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual")], max_length=16
                    ),
                ),
                ("sessions_processed", models.IntegerField(default=0)),
                ("entities_merged", models.IntegerField(default=0)),
                ("entities_pruned", models.IntegerField(default=0)),
                ("notes_updated", models.IntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_dream_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FutureQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intent", models.TextField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("time", "Time-based"),
                            ("event", "Event-based"),
                            ("manual", "Manual"),
                        ],
                        default="time",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fired", "Fired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="future_items",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "core_future_queue",
                "ordering": ["due_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_at"],
                        name="core_future_status_fae1a9_idx",
                    )
                ],
            },
        ),
    ]
