# Generated by Django 6.0.4 on 2026-04-17 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_future_queue_and_dream"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "schedule_kind",
                    models.CharField(
                        choices=[
                            ("at", "Run once at"),
                            ("every", "Every interval"),
                            ("cron", "Cron expression"),
                        ],
                        max_length=8,
                    ),
                ),
                ("schedule_value", models.CharField(max_length=128)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("stagger_seconds", models.PositiveIntegerField(default=0)),
                ("prompt", models.TextField(blank=True)),
                (
                    "light_context",
                    models.BooleanField(
                        default=False,
                        help_text="If true, run with stripped-down context (faster, no memory load).",
                    ),
                ),
                ("tools_allow", models.JSONField(blank=True, default=list)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("announce", "Announce on a channel"),
                            ("webhook", "POST to webhook URL"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("delivery_channel", models.CharField(blank=True, max_length=32)),
                ("delivery_to", models.CharField(blank=True, max_length=256)),
                ("delivery_webhook_url", models.URLField(blank=True)),
                (
                    "fail_alert_after",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Send an alert after N consecutive failures.",
                    ),
                ),
                (
                    "fail_alert_cooldown_seconds",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Min seconds between failure alerts to avoid spam.",
                    ),
                ),
                ("last_failure_alert_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_status", models.CharField(blank=True, max_length=16)),
                (
                    "running_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a worker picks up the job; cleared on completion. Used to guard against duplicate concurrent runs.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_cron_job",
                "ordering": ["next_run_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_run_at"],
                        name="core_cron_j_status_c905cc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CronRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Success"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                            ("timeout", "Timed out"),
                        ],
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=64)),
                ("provider_used", models.CharField(blank=True, max_length=32)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("error_text", models.TextField(blank=True)),
                (
                    "delivery_status",
                    models.CharField(
                        blank=True,
                        help_text="delivered | not-delivered | not-requested",
                        max_length=16,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.cronjob",
                    ),
                ),
            ],
            options={
                "db_table": "core_cron_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "-started_at"],
                        name="core_cron_r_job_id_6dba25_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="core_cron_r_status_652652_idx",
                    ),
                ],
            },
        ),
    ]
