# Generated by Django 5.2.13 on 2026-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cron_job_and_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='capture_output',
            field=models.BooleanField(default=True, help_text="If true, the agent's final response is stored in CronRun.summary."),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='delivery_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='model_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
