# Generated by Django 6.0.4 on 2026-04-17 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feeds_rss_feed",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("css_selector", models.CharField(max_length=500)),
                (
                    "cron_expression",
                    models.CharField(default="0 */6 * * *", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feeds_scrape_config",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RSSItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=500)),
                ("snippet", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_new", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="feeds.rssfeed",
                    ),
                ),
            ],
            options={
                "db_table": "feeds_rss_item",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feed", "published_at"],
                        name="feeds_rss_i_feed_id_d337b4_idx",
                    ),
                    models.Index(
                        fields=["is_new"], name="feeds_rss_i_is_new_d17d21_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed", "url"), name="uniq_feed_item_url"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapeResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("has_changed", models.BooleanField(default=False)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="feeds.scrapeconfig",
                    ),
                ),
            ],
            options={
                "db_table": "feeds_scrape_result",
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["config", "scraped_at"],
                        name="feeds_scrap_config__1f101a_idx",
                    ),
                    models.Index(
                        fields=["has_changed"], name="feeds_scrap_has_cha_cb51b7_idx"
                    ),
                ],
            },
        ),
    ]
