# Generated by Django 6.0.4 on 2026-04-17 10:31

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_tasks_and_audit"),
        ("memory", "0001_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("project", "Project"),
                            ("company", "Company"),
                            ("preference", "Preference"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entities",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "memory_entity",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["entity_type"], name="memory_enti_entity__44b174_idx"
                    ),
                    models.Index(fields=["name"], name="memory_enti_name_22d9f4_idx"),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="entity_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "name"), name="uniq_entity_type_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NoteIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("content_preview", models.TextField(blank=True, default="")),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "memory_note_index",
                "ordering": ["-updated_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="note_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary_text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "memory_session_embedding",
                "ordering": ["-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="sess_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
